baseURL: https://lmorillas.github.io
languageCode: es
title: 'lmorillas'
theme: blowfish


# module:
#   imports:
#     - path: github.com/nunocoracao/blowfish
#       disable: false  

publishDir: docs
